#Request
int32 roll
int32 pitch
int32 yaw
float32 acc_x
float32 acc_y
float32 acc_z
float32 gyro_x
float32 gyro_y
float32 gyro_z
float32 mag_x
float32 mag_y
float32 mag_z
float32 alt
float32 battery
int32 rssi
---
#Response
int64 rc_roll
int64 rc_pitch
int64 rc_yaw
int64 rc_throttle
int64 rc_aux1
int64 rc_aux2
int64 rc_aux3
int64 rc_aux4
